"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: idl

"""

from ._dds-fmu import MyCustomSignalStructureInput, MyCustomSignalStructureOutput
__all__ = ["MyCustomSignalStructureInput", "MyCustomSignalStructureOutput", ]
