"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: idl
  IDL file: dds-fmu.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types



@dataclass
@annotate.final
@annotate.autoid("sequential")
class MyCustomSignalStructureInput(idl.IdlStruct, typename="idl.MyCustomSignalStructureInput"):
    fmu_output_value: types.uint32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class MyCustomSignalStructureOutput(idl.IdlStruct, typename="idl.MyCustomSignalStructureOutput"):
    my_state: bool
    my_value: types.int32
    my_percentage: types.float64
    my_letter: types.char
    my_text: str


